### ISSUE TITLE
Migration to embedded-stm32f4 run time

### ISSUE THREAD

**Issue by patroclo77** [AdaCore/Certyflie#23]
Hello,
Would it be possible for you to migrate the code to the more recent run-time 'embedded-stm32f4' rather than using the old ' ravenscar-full-stm32f4'?

I am facing quite a few issues:

![image](https://github.com/user-attachments/assets/b15801de-7942-4e05-aeec-703ee9ac26f6)

Thanks.

**Comment by Fabien-Chouteau** [comment]
Hello @patroclo77, This project is no longer maintained, and we don't plan to update it at this point.

Feel free to fork and do your own modifications.

Best,
