### ISSUE TITLE
Mistranslation in Madgwick algorithm

### ISSUE THREAD

**Issue by simonjwright** [AdaCore/Certyflie#3]
In `modules/madgwick/sensfusion6.adb:367`,

    S1 := Q1_X4 * Q2_Q2 - Q3_X2 * Norm_Ax + 4.0 * Q0_Q0 * Q1 -
      Q0_X2 * Norm_Ay - Q1_X4 + Q1_X8 * Q1_Q1 +
        Q1_X8 * Q2_Q2 + Q1_X4 * Norm_Az;

appears to be a mistranslation of the C code from http://x-io.co.uk/open-source-imu-and-ahrs-algorithms/, at MadgwickAHRS.c:

    s1 = _4q1 * q3q3 - _2q3 * ax + 4.0f * q0q0 * q1 - _2q0 * ay - _4q1 + _8q1 * q1q1 + _8q1 * q2q2 + _4q1 * az;

(the second term should be `Q3_Q3`, not `Q2_Q2`).

(The Ada is clearly a translation of the referenced C code, since - aside from using the identical algorithms - the spelling errors in the original C appear in the Ada, e.g. "decent" for "descent").

**Comment by Fabien-Chouteau** [comment]
Thanks for reporting this issue, let's discuss in the pull request (#4).
